### ISSUE TITLE
Yarn build fails in quickstart-with-relay-modern

### ISSUE THREAD

**Issue by NicoLedwith** [graphcool-examples/react-graphql#25]
Throws an error regarding undefined variables
```
yarn build v0.24.6
$ node scripts/build.js 
Creating an optimized production build...
Failed to compile.

./src/CreatePostMutation.js
  Line 49:  'viewerId' is not defined  no-undef
  Line 61:  'viewerId' is not defined  no-undef

Search for the keywords to learn more about each error.

error Command failed with exit code 1.
```

**Comment by panayi** [comment]
Looks like a typo - should be a string `'viewerId'`, instead of `viewerId`:

![image](https://user-images.githubusercontent.com/707005/27572780-954ac00a-5b16-11e7-9449-263db0f90e92.png)

This fixes the above error and loads the app. However, once I try to create a post I get this error:

![image](https://user-images.githubusercontent.com/707005/27572809-cb8e5e42-5b16-11e7-90b8-a29ea710db9c.png)

**Comment by gojutin** [comment]
If anyone is still having issues with this, you can just pass the viewerId as the third argument in the `CreatePostMutation` function in `CreatePostMutation.js`. It looks like they may have accidentally removed it in the last commit. 

`export default function CreatePostMutation(description, imageUrl, viewerId, callback)`

**Comment by gojutin** [comment]
Also, in order to be able to create new posts, the `createPage` component will need to be wrapped in a `QueryRenderer` container and the `viewerId`  will need to be fetched via a query and passed to the `CreatePostMutation` through the `_handlePost` method. They walk you through the entire process on their YouTube video starting at 39:26. 

https://youtu.be/XeALXh37WeU?t=39m26s[https://youtu.be/XeALXh37WeU?t=39m26s]

**Comment by marktani** [comment]
Hey @gojutin, did you manage to solve this problem? Would love to review a PR because I couldn't get it to run 😅

**Comment by gojutin** [comment]
Hi @marktani , I have not issued a PR but I did fork the project with the changes [here](https://github.com/gojutin/react-graphql). The changes include:

- Added a `QueryRenderer` to the `createPage ` component. 
- Fetched the `viewerId` via a query and passed it to the `CreatePostMutation` through the `_handlePost` method.
https://youtu.be/XeALXh37WeU?t=39m26s

- Updated to React Router v4.
- Moved components and mutations to their own directories.
- Added `relay-start` script that runs the relay-compiler, then starts the dev server.
`yarn run relay-start`

If anyone would like me to issue a PR, please just let me know and I will be happy to. I just wasn’t sure with all of the changes.

**Comment by nikolasburk** [comment]
Hey @gojutin, the issue should be fixed now thanks to the PR by @latik. However, I'd also love to incorporate the other changes you listed - feel free to create a PR for them as well :)

**Comment by gojutin** [comment]
Hi @nikolasburk, I made the PR and hopefully did it right. I am still kind of new to GitHub so you might want to double check that there's nothing funny going on. The diff is huge because of my changes and the fact that I did not commit the `__generated__` directories that are created during the Relay compile step.
