### ISSUE TITLE
bad relay version in quickstart-with-relay

### ISSUE THREAD

**Issue by smmoosavi** [graphcool-examples/react-graphql#30]
after run `yarn` in quickstart-with-relay I get following question:

```
warning Lockfile has incorrect entry for "react-relay@1.0.1-alpha.2". Ignoring it.
Couldn't find any versions for "react-relay" that matches "1.0.1-alpha.2"
? Please choose a version of "react-relay" from this list:
```

first I download this project from `https://serverless-github-example-proxy.s3.amazonaws.com/` after tutorial with same issue

**Comment by nikolasburk** [comment]
Thanks a lot for creating this issue! We'll actually remove the `quickstart-with-relay` example in favor of the `quickstart-with-relay-modern` one as we don't want to encourage people to start out with Relay Classic any more. Since the issue referred to the Relay Classic example, it'll be solved by just removing the example!
